relayer_urls = ["wss://relayer.pyth-lazer-staging.dourolabs.app/v1/transaction"]
publish_keypair_path = "./config/secrets/agent-lazer-keypair.json"
authorization_token = ""
listen_address = "0.0.0.0:8910"
publish_interval_duration = "25ms"